### PR TITLE
Updairng LDAP API to 2.1.3

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by elecharny** [comment]
@coheigea I have to check. I think I fixed this issue locally.

**Comment by elecharny** [comment]
@coheigea Applied the local fixes I had.

**Comment by coheigea** [comment]
@elecharny Thanks it's better, but the apacheds-osgi-integ all fail for me with e.g.:

[ERROR] org.apache.directory.server.osgi.integ.ServerJdbmPartitionOsgiTest.null
[ERROR]   Run 1: ServerJdbmPartitionOsgiTest » IllegalAccess tried to access method org.apache.commons.logging.LogFactory.<init>()V from class org.apache.commons.logging.impl.SLF4JLogFactory
[ERROR]   Run 2: ServerJdbmPartitionOsgiTest » NoClassDefFound Could not initialize class shaded.org.apache.http.conn.ssl.SSLConnectionSocketFactory

**Comment by elecharny** [comment]
Can you past a mvn --version?

**Comment by coheigea** [comment]
It seems this is a local error so I will close this PR. I tagged you Emmanuel in another issue which the build is throwing.

**Pull request closed without merging**
