### PR TITLE
Adding stacktrace

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by coheigea** [comment]
@elecharny The stack trace is:

org.apache.directory.api.ldap.model.exception.LdapTlsHandshakeException: ERR_04120_TLS_HANDSHAKE_ERROR The TLS handshake failed, reason: Unspecified: null
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSecured(LdapNetworkConnection.java:849)
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.connect(LdapNetworkConnection.java:1009)
	at org.apache.directory.shared.client.api.LdapSSLConnectionTest.lambda$testSslConnectionNonSslPort$6(LdapSSLConnectionTest.java:560)

**Comment by elecharny** [comment]
Note that we have issues with Java 11 on the same test, when it passes on Java 8.

At this point, we need to add java 17 and 20 to our build system and I need to check what's wrong with the 11 version on my laptop.

**Comment by elecharny** [comment]
Wow, not very helpful stack trace :/
The code is:

`            boolean isSecured = handshakeFuture.get( connectTimeout, TimeUnit.MILLISECONDS );

            if ( !isSecured )
            {
                // check for a specific cause
                Throwable cause = connectionFuture.getException();
                
                if ( cause == null && connectionFuture.getSession() != null )
                {
                    cause = ( Throwable ) connectionFuture.getSession().getAttribute( EXCEPTION_KEY );
                }
                
                // Cancel the latch
                connectionCloseFuture.complete( 0 );

                // if there is no cause assume timeout
                if ( cause == null )
                {
                    throw new LdapException( TIME_OUT_ERROR );
                }

                throw new LdapTlsHandshakeException( I18n.err( I18n.ERR_04120_TLS_HANDSHAKE_ERROR ), cause );
            }
`
We have to find out what 'cause' is, and that requires some modification in the LDAP API. Working on that.

**Comment by elecharny** [comment]
Added some info in the LDAP API 2.1.4-SNAPSHOT.

@coheigea  Could you test with it?

**Comment by coheigea** [comment]
@elecharny Here it is:

rg.apache.directory.api.ldap.model.exception.LdapTlsHandshakeException: ERR_04120_TLS_HANDSHAKE_ERROR The TLS handshake failed, reason: Undefined, WriteToClosedSessionException: null
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSecured(LdapNetworkConnection.java:849)
	at org.apache.directory.ldap.client.api.LdapNetworkConnection.connect(LdapNetworkConnection.java:1009)
	at org.apache.directory.shared.client.api.LdapSSLConnectionTest.lambda$testSslConnectionNonSslPort$6(LdapSSLConnectionTest.java:560)

**Comment by elecharny** [comment]
Ok, thanks.

So MINA is throwing this exception when we try to write some data to a session which has -rightfully - been closed. That makes sense.

AllI need to do now is to 'qualify' this exception and return the associated message in the LdapTlsHandshakeException so that the AssertThat calls don't fail.

**Comment by elecharny** [comment]
Side note: I don't get this error on my laptop, but it might be a timing issue: the time it takes to process the closing session - and the resulting exception - may explain why I get the expected exception, and you don't.

I have a 5 years old Mac Book Pro, 2,9 GHz Intel Core i9. What is your computer?

**Comment by coheigea** [comment]
I don't have it on my recent Mac Book Pro either, the error is reported in the GitHub Action builder.

**Comment by coheigea** [comment]
Update to Mina https://github.com/apache/directory-server/pull/95 and everything seems OK, so I re-enabled the test and closed the issue.

**Pull request closed without merging**
