### PR TITLE
Ehcache v3 update

### PR DESCRIPTION
**Pull request by rsandidfc**
This pull contains changing ehcache 2.10.4 to 3.6.1. ehcache v3 is very different architecturally from v2. Several configuration options were removed, and several more programmatic capabilities removed. v3 also uses generics to stronger type cache instances.

The first place to look to understand the changes made are in /directory-server/core-api/src/main/resources/directory-cacheservice.xml. There is no longer a "default" cache, so each cache used by ApacheDS is explicitly defined. The configuration properties that simply no longer map into the v3 config I left commented out. 

There was a lot more work here than I thought. Someone needs to look at this and the changes I had to make to get everything to compile and unit test and vet them all.

It may simply be easier to implement JSR-107 entirely and make caching pluggable.

### CODE REVIEW

**Comment by elecharny** [comment]
I fixed the NPE, in {{AbstractBtreePartition}}, {{fetch()}} method : 
`
    public Entry fetch( PartitionTxn partitionTxn, String id ) throws LdapException
    {
        try
        {
            rwLock.readLock().lock();

            if ( id == null )
            {
                id = "";
            }
            
            Dn dn = buildEntryDn( partitionTxn, id );
`

Now, there are some other issues, OSGi related.

On it.

**Comment by elecharny** [comment]
Ok, after many {{pom.xml}} updates, I think I'm good to go with ehcache 3.6.1.

I'll run a last full build first, to be sure.

**Comment by rsandidfc** [comment]
I was able to do a full build but some of the junit tests were throwing exceptions in the beforeclass methods, sorry I thought I’d fixed them all :-)

A few of the tests that were very specifically testing the cache configurations no longer work with the more limited runtime controls of ehcache3.

**Comment by elecharny** [comment]
Merged into trunk !

It was quite a fight... Fixing OSGi tests were just a nightmare, took me hours.

**Pull request closed without merging**
